### ISSUE TITLE
请求： 更新jitpack上的版本

### ISSUE THREAD

**Issue by CodeReadOnlyUser** [wuyouuuu/wytrace#1]
在 https://issuetracker.google.com/issues/311251587 看到这个库可以修复Android 14 debug卡顿的问题，想试用一下，发现jitpack上的版本 ```implementation 'com.github.wuyouuuu:wytrace:1.0.0'``` 不包含修复。希望能更新一下版本，方便不想自行编译的用户。

**Comment by wuyouuuu** [comment]
done
